### ISSUE TITLE
Tag releases to make project godep friendly.

### ISSUE THREAD

**Issue by renatoathaydes** [atotto/clipboard#24]
Hello. Could you please tag releases so that `dep` can use that information to make builds more reproducible?

Check https://github.com/golang/dep.

Currently, using your project with godep I get this in the toml file:

```toml
[[constraint]]
  branch = "master"
  name = "github.com/atotto/clipboard"
```

With a tag, it would constrain the dependency to that tag.
